version: '3'
services:
  api:
    container_name: flask-container
    build: ./backend
    entrypoint: python model/main.py
    env_file:
      - .env
    ports:
      - '7002:7002'
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
  
  database:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: unbxd
      POSTGRES_DB: unbxd
  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080
      